version: "3"

networks:
    nginx_net:
      driver: bridge

services:

  nginx:
    image: nginx:1.25.2-alpine
    restart: unless-stopped
    container_name: nginx
    ports:
      - "8080:8080"
    depends_on:
      - db
      - api-agendamentos
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx_net

  db:
    image: postgres:latest
    restart: always
    environment:
      DB_URI: ${DB_URI}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    container_name: "db"
    ports:
      - "27017:27017"
    networks:
      - nginx_net

  api-agendamentos:
    image: daniel00dev/spring-boot-api-agendamentos:1.0
    container_name: agendamentos
    restart: unless-stopped
    env_file:
      - ./env/api.env
    environment:
      - SERVER_PORT=8090
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nginx_net






