version: "3"
services:
  daniel00mongodb:
    image: mongo:latest
    container_name: "daniel00mongodb"
    ports:
      - "27017:27017"
  springboot-agendamentos:
    image: daniel00dev/spring-boot-api-agendamentos:1.0
    container_name: springboot-agendamentos
    ports:
      - "8090:8090"

    links:
      -  daniel00mongodb




