version: "3"

networks:
    nginx_net:
      driver: bridge

services:

#  nginx:
#    image: nginx:latest
#    ports:
#      - "8000:8000"
#    volumes:
#      - ./etc/nginx/nginx.conf:/usr/share/nginx/html
#    networks:
#      -  nginx_net

  daniel00mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_DB_URI: ${DB_URI}
      MONGO_DB_USERNAME: ${DB_USER}
      MONGO_DB_PASSWORD: ${DB_PASSWORD}
    container_name: "daniel00mongodb"
    ports:
      - "27017:27017"
    networks:
      - nginx_net

  springboot-agendamentos:
    image: daniel00dev/spring-boot-api-agendamentos:1.0
    container_name: springboot-agendamentos
    ports:
      - "8090:8090"
    networks:
      - nginx_net

    links:
      -  daniel00mongodb




