apiVersion: apps/v1
kind: Deployment
metadata:
  name: agendar-deployment
  labels:
    app: agendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agendar
  template:
    metadata:
      labels:
        app: agendar
    spec:
      containers:
        - name: agendar
          image: daniel00dev/spring-boot-api-agendamentos:1.0
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: agendar-service
spec:
  selector:
    app: agendar
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /user-api(/|$)(.*) #/user-api/getAll
            backend:
              service:
                name: agendar
                port:
                  number: 8090
---










